version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
    - dependency-name: numpy
